services:
  - type: web
    name: bach
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: REPO_BRANCH
        value: main
  - type: web
    name: calendar
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: REPO_BRANCH
        value: main
      - key: APP_MODE
        value: calendar
